export const ERROR_CODES = {
  THREAD_NOT_FOUND: 'T101',
  INVALID_STATE_TRANSITION: 'T102',
  CIRCULAR_REFERENCE: 'T201',
  REFERENCE_TARGET_CORRUPTED: 'T202',
  MERGE_CONFLICT_UNRESOLVED: 'T301',
  MERGE_VALIDATION_FAILED: 'T302',
  APPROVAL_TIMEOUT: 'T401',
  PERMISSION_DENIED: 'T402',
  FILE_LOCK_FAILED: 'T501',
  JSON_PARSE_FAILED: 'T502',
  OBJECTIVE_NOT_FOUND: 'T601',
  OBJECTIVE_NOT_COMPLETABLE: 'T602',
  INTERNAL_ERROR: 'T901',
  UNKNOWN_ERROR: 'T902',
} as const;

export const WARNING_CODES = {
  REFERENCE_TARGET_UNAVAILABLE: 'W202',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
export type WarningCode = (typeof WARNING_CODES)[keyof typeof WARNING_CODES];
