import fs from 'node:fs/promises';
import path from 'node:path';
import type { LeslieCore } from '@vibe-x-ai/leslie-core';
import { getGlobalConfigPath } from '../../config/env-loader.js';

const ANTHROPIC_VARS = [
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_BASE_URL',
  'ANTHROPIC_DEFAULT_HAIKU_MODEL',
  'ANTHROPIC_DEFAULT_OPUS_MODEL',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
  'ANTHROPIC_MODEL',
] as const;

const DEFAULT_TEMPLATE = `# Leslie global env (kwaipilot)
# Generated by: leslie config init

ANTHROPIC_AUTH_TOKEN=Test
ANTHROPIC_BASE_URL=http://localhost:3000
ANTHROPIC_DEFAULT_HAIKU_MODEL=kwaipilot-default
ANTHROPIC_DEFAULT_OPUS_MODEL=kwaipilot-default
ANTHROPIC_DEFAULT_SONNET_MODEL=kwaipilot-default
ANTHROPIC_MODEL=kwaipilot-default
`;

export async function runConfigInit(
  _core: LeslieCore,
  flags: Record<string, unknown>,
): Promise<{ success: boolean; data: Record<string, unknown> }> {
  const targetPath = getGlobalConfigPath();
  const fromEnv = flags['from-env'] === true;
  const force = flags.force === true;

  const dir = path.dirname(targetPath);
  await fs.mkdir(dir, { recursive: true });

  let content: string;
  if (fromEnv) {
    const lines = ANTHROPIC_VARS.map((key) => {
      const val = process.env[key] ?? '';
      return `${key}=${val}`;
    });
    content = `# Leslie global env (from current process.env)\n# Generated by: leslie config init --from-env\n\n${lines.join('\n')}\n`;
  } else {
    content = DEFAULT_TEMPLATE;
  }

  try {
    await fs.access(targetPath);
    if (!force) {
      return {
        success: true,
        data: {
          path: targetPath,
          from_env: fromEnv,
          skipped: true,
          message: 'File exists, use --force to overwrite',
        },
      };
    }
  } catch {
    // File not exist, proceed
  }

  await fs.writeFile(targetPath, content, 'utf-8');
  return {
    success: true,
    data: { path: targetPath, from_env: fromEnv },
  };
}
